<a href="https://colab.research.google.com/github/ajay290194/IIT-M/blob/main/BA_GA_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train = pd.read_csv('/content/data_LR_train.csv')
test = pd.read_csv('/content/data_LR_test.csv')

In [3]:
train.head()

Tier  FICO  Term    Amount  Previous_Rate  Competition_rate  Rate  \
0     1   783    36  16378.00              0              3.69  3.69   
1     2   711    48  28322.00              0              5.49  4.89   
2     1   773    36   9500.00              0              3.99  3.99   
3     1   743    72  24078.00              5              6.09  4.69   
4     1   762    72  14999.99              0              5.75  5.69   

   Cost_Funds  Partner Bin  Car_Type_N  Car_Type_R  Car_Type_U  Accept  
0      1.1200            1           1           0           0     0.0  
1      1.8200            1           1           0           0     0.0  
2      1.1100            3           1           0           0     0.0  
3      1.1100            1           0           1           0     0.0  
4      1.1463            3           0           0           1     0.0

In [4]:
train.shape

(23970, 13)

In [5]:
train.describe()

Tier          FICO          Term         Amount  Previous_Rate  \
count  23970.000000  23970.000000  23970.000000   23970.000000   23970.000000   
mean       1.917772    727.125282     56.842053   26036.637091       1.756863   
std        1.047117     44.811054     11.224998   11205.186313       3.485156   
min        1.000000    601.000000     36.000000    4526.620000       0.000000   
25%        1.000000    692.000000     48.000000   17814.250000       0.000000   
50%        2.000000    726.000000     60.000000   25000.000000       0.000000   
75%        3.000000    763.000000     60.000000   33000.000000       0.000000   
max        4.000000    852.000000     72.000000  100000.000000      23.000000   

       Competition_rate          Rate    Cost_Funds   Partner Bin  \
count      23970.000000  23970.000000  23970.000000  23970.000000   
mean           4.807391      5.619706      1.329026      2.032457   
std            0.589866      1.545711      0.279312      0.909267   
min            2.990000      2.450000      1.020000      1.000000   
25%            4.390000      4.490000      1.110000      1.000000   
50%            4.790000      5.090000      1.246300      2.000000   
75%            5.190000      6.390000      1.418800      3.000000   
max            6.450000     11.550000      2.127000      3.000000   

         Car_Type_N    Car_Type_R    Car_Type_U        Accept  
count  23970.000000  23970.000000  23970.000000  23969.000000  
mean       0.572966      0.229871      0.197163      0.222412  
std        0.494658      0.420758      0.397865      0.415875  
min        0.000000      0.000000      0.000000      0.000000  
25%        0.000000      0.000000      0.000000      0.000000  
50%        1.000000      0.000000      0.000000      0.000000  
75%        1.000000      0.000000      0.000000      0.000000  
max        1.000000      1.000000      1.000000      1.000000

In [6]:
train['Accept'].value_counts(normalize=True)

0.0    0.777588
1.0    0.222412
Name: Accept, dtype: float64

In [7]:
train.columns

Index(['Tier', 'FICO', 'Term', 'Amount', 'Previous_Rate', 'Competition_rate',
       'Rate', 'Cost_Funds', 'Partner Bin', 'Car_Type_N', 'Car_Type_R',
       'Car_Type_U', 'Accept'],
      dtype='object')

In [8]:
features = ['Tier', 'FICO', 'Term', 'Amount', 'Previous_Rate', 'Competition_rate',
       'Rate', 'Cost_Funds', 'Partner Bin', 'Car_Type_N', 'Car_Type_R',
       'Car_Type_U']
       
target = ['Accept']

In [9]:
X_train = train[features]
y_train = train[target]

In [10]:
X_test = test[features]
y_test = test[target]

In [11]:
len(train.columns)

13

In [12]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [13]:
#logreg.fit(X_train,y_train)
y_train = y_train.fillna(0)

In [14]:
logreg.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [15]:
logreg.coef_

array([[-2.25879717e-01, -1.01052086e-03,  6.13804732e-02,
        -9.91610091e-05,  1.36776983e-01,  2.59689105e-01,
        -3.75552284e-01,  1.35950589e-02, -3.88751295e-01,
        -6.75643667e-01, -8.00938110e-02,  7.54795869e-01]])

In [16]:
fico = logreg.coef_[0][1]
#print(fico)
o = np.exp(fico)
print(o)

0.998989989541625


In [17]:
y_pred = logreg.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[18093,  1371],
       [ 3394,  2142]])

In [19]:
Accuracy = (18093+2142)/(18093+1371+3394+2142)
Accuracy

0.8094

In [20]:
#precision for those who will not take the loan
precision = 18093/(18093+3394)
precision

0.8420440266207474

In [21]:
recall = 2142/(2142+1371)
recall

0.609735269000854

In [22]:
#precision for those who will take the loan
prec = 2142/(2142+1371)
prec

0.609735269000854

In [23]:
rec = 2142/(2142+3394)
rec

0.38692196531791906

In [24]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

In [25]:
a1 = accuracy_score(y_test, y_pred)
a1

0.8094

In [26]:
p1 = precision_score(y_test, y_pred, pos_label=1)
p1

0.609735269000854

In [27]:
r1 = recall_score(y_test, y_pred, pos_label=1)
r1

0.38692196531791906

In [28]:
y_p = logreg.predict(X_train)

In [29]:
a2 = accuracy_score(y_train, y_p)
a2

0.8136420525657071

## **NEXT QUESTION**

In [30]:
y = np.array([0,0,0,0,0,1])
y1 = np.array([0.122522,0.137083,0.208256,0.054945,0.116276,0.057915])
y,y1

(array([0, 0, 0, 0, 0, 1]),
 array([0.122522, 0.137083, 0.208256, 0.054945, 0.116276, 0.057915]))

In [31]:
y1_mod = []
for i in y1:
  if i>=0.5:
    y1_mod.append(1)
  else:
    y1_mod.append(0)
y1_m = np.array(y1_mod)
y1_m


array([0, 0, 0, 0, 0, 0])

In [32]:
a3 = accuracy_score(y,y1_m)
a3

0.8333333333333334

In [33]:
r3 = recall_score(y,y1_m,pos_label=1)
p3 = precision_score(y,y1_m,pos_label=1)
r3,p3

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(0.0, 0.0)

In [34]:
y2_mod = []
for i in y1:
  if i>=0.2:
    y2_mod.append(1)
  else:
    y2_mod.append(0)
y2_m = np.array(y2_mod)
y2_m


array([0, 0, 1, 0, 0, 0])

In [35]:
a4 = accuracy_score(y,y2_m)
r4 = recall_score(y,y2_m,pos_label=1)
p4 = precision_score(y,y2_m,pos_label=1)
a4,r4,p4

(0.6666666666666666, 0.0, 0.0)